### ISSUE TITLE
No links marking bad

### ISSUE THREAD

**Issue by HPaulson** [n1try/safe-browse-url-lookup#1]
Hey is this package still working? No links no matter what are marking as isMalicious... I've tried links chrome blocks (gives security warning), IP grabbers, malware, instant downloads, and even links on the google secure search list.

**Comment by muety** [comment]
Did you try to call the API directly? I just ran a few raw queries against [API v4](https://developers.google.com/safe-browsing/v4) with domains from [Malwaredomains.com](http://mirror1.malwaredomains.com/files/domains.txt) and did not get a match either. Maybe something's wrong with Google's API?

**Comment by HPaulson** [comment]
Not too sure what that site is, however I do think this could be an issue with the google api. I’ve been using this package for quite a long time, however it’s strange that the Google API still gives API tokens, and has documentation up.., nothing I see for it not being updated. https://developers.google.com/safe-browsing/v4

**Comment by HPaulson** [comment]
They also have an official package for GO that uses this API that I’ve also used, that was committee  to as recently as 7 months ago. So, I’m assuming the API is still in use and updated. https://github.com/google/safebrowsing

**Comment by muety** [comment]
I briefly investigated this again. Looks like library and API are working properly. I checked with Google's test URL (see updated Readme) and a few domains from [Openfish](https://openphish.com/) and got correct results.

**Comment by muety** [comment]
Is it still a problem or can we close this issue?

**Comment by HPaulson** [comment]
Sorry, forgot about this one haha. After trying links from Openfish I can confirm that the issue is not the api or package, rather it is with the lack of support for certain sites on googles side. Thanks for the help!
